"""fix parent_taskId to null

Revision ID: 8ef0f8b99dae
Revises: 98eb214cc2de
Create Date: 2024-06-09 17:43:34.628287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef0f8b99dae'
down_revision: Union[str, None] = '98eb214cc2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tasks', 'parent_task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tasks', 'parent_task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
